In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv("Stage 1 Score sheet da.xlsx - Sheet1.csv")
df2 = pd.read_csv("Stage 2 Score Sheet DA.xlsx - Stage 2 Score.csv")

In [22]:
df1.shape,df2.shape

((517, 5), (279, 6))

In [23]:
517-279

238

In [4]:
df1.head()

,Slack Display Name,Slack Email,Total,Pass/Fail,Premium Promotion
0,Ruby_C,chizobaokakpu65@gmail.com,8.95,Pass,NaN
1,KwasakuS,kwasaku6@gmail.com,8.80,Pass,NaN
2,Anyanwu Emmanuella Eberechukwu,anastasiaanyanwu1@gmail.com,8.70,Pass,NaN
3,Dominic Kishatingunimye,dominiqkish@gmail.com,8.50,Pass,NaN
4,EnochA 1️⃣,apehenoch@gmail.com,8.30,Pass,NaN

In [5]:
df2.head()

,Slack Display Name,Slack Email,TASK A Total,Task B Total,Cummulative Score,Pass/Fail
0,jaycarlx,molokwuchibuzorchristian@gmail.com,46.27,40.0,8.63,Pass
1,MayowaO,NaN,40.50,44.5,8.50,Pass
2,Mariam-O,Princesstonni01@gmail.con,42.00,41.0,8.30,Pass
3,el3ctronar,paulonko000@gmail.com,41.56,40.7,8.23,Pass
4,MosunmolaO,adenijimosunmolao@gmail.com,42.00,40.0,8.20,Pass

In [11]:
df1.columns = ['Slack Display Name', 'Slack Email', 'Stage1_Total', 'Stage1_Pass_Fail',
       'Premium Promotion']

In [13]:
df2.columns =['Slack Display Name', 'Slack Email', 'Stage2_Total', 'Task B Total',
       'Stage2_Total', 'Stage2_Pass_Fail']

In [19]:
newdf = pd.merge(df1,df2,on = "Slack Display Name",how = "left")[["Slack Display Name", "Slack Email_x", "Stage1_Total", "Stage1_Pass_Fail", "Stage2_Total", "Stage2_Pass_Fail"]]

In [20]:
newdf.head()

,Slack Display Name,Slack Email_x,Stage1_Total,Stage1_Pass_Fail,Stage2_Total,Stage2_Total,Stage2_Pass_Fail
0,Ruby_C,chizobaokakpu65@gmail.com,8.95,Pass,39.6,6.26,Fail
1,KwasakuS,kwasaku6@gmail.com,8.80,Pass,41.5,7.19,Pass
2,KwasakuS,kwasaku6@gmail.com,8.80,Pass,30.0,7.05,Pass
3,Anyanwu Emmanuella Eberechukwu,anastasiaanyanwu1@gmail.com,8.70,Pass,40.0,4.50,Fail
4,Dominic Kishatingunimye,dominiqkish@gmail.com,8.50,Pass,32.5,5.50,Fail

In [21]:
newdf.isnull().sum()

Slack Display Name      0
Slack Email_x           0
Stage1_Total            0
Stage1_Pass_Fail        0
Stage2_Total          307
Stage2_Total          306
Stage2_Pass_Fail      306
dtype: int64

In [24]:
newdf.sort_values("Slack Display Name")

,Slack Display Name,Slack Email_x,Stage1_Total,Stage1_Pass_Fail,Stage2_Total,Stage2_Total,Stage2_Pass_Fail
58,--Fortunate--,lovepaul869@gmail.com,7.50,Pass,40.19,7.02,Pass
203,4tuneDee,chidaddy.fortune@gmail.com,6.00,Pass,30.50,3.05,Fail
162,@La'dimz,ohalezimlindachidinma@gmail.com,6.20,Pass,NaN,NaN,NaN
325,@kiitan of Lagos,mubarakolaitan1@gmail.com,5.25,Fail,NaN,NaN,NaN
309,A. Kajo,kareemojoaishah@gmail.com,5.50,Fail,NaN,NaN,NaN
...,...,...,...,...,...,...,...
130,tunmise_ad,tunmiseadedeji2019@gmail.com,6.50,Pass,NaN,NaN,NaN
265,ugo_c_ugo,gloryadigwe33@gmail.com,6.00,Pass,NaN,NaN,NaN
441,vee,violet.ehiaguina26@gmail.com,3.00,Fail,NaN,NaN,NaN
494,yunana,danharuna04@gmail.com,0.00,Fail,NaN,NaN,NaN
291,yunana,danharuna04@gmail.com,5.50,Fail,NaN,NaN,NaN

In [39]:
def score_grade(score):
    try:
        if score > 8:
            return "Star perf"
        elif score > 7.5:
            return "Great guy"
        elif score > 6.9:
            return "Just there"
        else:
            return "Fail"
    except:
        return "Fail"

In [32]:
newdf["Stage1_perf_grade"] = newdf["Stage1_Total"].apply(score_grade)

In [ ]:
newdf.head()

,Slack Display Name,Slack Email_x,Stage1_Total,Stage1_Pass_Fail,Stage2_Total,Stage2_Total,Stage2_Pass_Fail,Stage1_perf_grade
0,Ruby_C,chizobaokakpu65@gmail.com,8.95,Pass,39.6,6.26,Fail,Star perf
1,KwasakuS,kwasaku6@gmail.com,8.80,Pass,41.5,7.19,Pass,Star perf
2,KwasakuS,kwasaku6@gmail.com,8.80,Pass,30.0,7.05,Pass,Star perf
3,Anyanwu Emmanuella Eberechukwu,anastasiaanyanwu1@gmail.com,8.70,Pass,40.0,4.50,Fail,Star perf
4,Dominic Kishatingunimye,dominiqkish@gmail.com,8.50,Pass,32.5,5.50,Fail,Star perf

In [34]:
newdf["Stage1_perf_grade"].value_counts()

Stage1_perf_grade
Fail          410
Just there     71
Great guy      29
Star perf      11
Name: count, dtype: int64

In [37]:
newdf = newdf.fillna(0)

In [42]:
newdf.columns = ['Slack Display Name', 'Slack Email_x', 'Stage1_Total',
       'Stage1_Pass_Fail', 'Stage2_Total_x', 'Stage2_Total', 'Stage2_Pass_Fail',
       'Stage1_perf_grade']

In [43]:
newdf["Stage2_perf_grade"] = newdf["Stage2_Total"].apply(score_grade)

In [44]:
newdf.head()

,Slack Display Name,Slack Email_x,Stage1_Total,Stage1_Pass_Fail,Stage2_Total_x,Stage2_Total,Stage2_Pass_Fail,Stage1_perf_grade,Stage2_perf_grade
0,Ruby_C,chizobaokakpu65@gmail.com,8.95,Pass,39.6,6.26,Fail,Star perf,Fail
1,KwasakuS,kwasaku6@gmail.com,8.80,Pass,41.5,7.19,Pass,Star perf,Just there
2,KwasakuS,kwasaku6@gmail.com,8.80,Pass,30.0,7.05,Pass,Star perf,Just there
3,Anyanwu Emmanuella Eberechukwu,anastasiaanyanwu1@gmail.com,8.70,Pass,40.0,4.50,Fail,Star perf,Fail
4,Dominic Kishatingunimye,dominiqkish@gmail.com,8.50,Pass,32.5,5.50,Fail,Star perf,Fail

In [25]:
newdf.to_csv('newdf.csv',index = False)

In [ ]:
import re

def clean_slack_name(name):
    if pd.isna(name): 
        return ""
    name = str(name).strip()
     # Remove @ prefix
    if sname.startswith('@'):
        name = name[1:].strip()

In [ ]:
import re

def clean_slack_name(name):
    if pd.isna(name): 
        return ""
    name = str(name).strip()
    
    # Remove @ prefix
    if name.startswith('@'):
        name = name[1:].strip()
    
    # Remove trailing numbers, emojis, symbols like 1️⃣, 2️⃣, etc.
    # Also remove " (1)", " [1]", etc.
    name = re.sub(r'[0-9]+️⃣|\s*\([0-9]+\)|\s*\[[0-9]+\]|\s*[1-9]$', '', name)
    name = re.sub(r'\s*;.*', '', name)  # e.g., "FaithA ;)"
    name = re.sub(r'\s+\d+$', '', name)  # e.g., "FaithCK 4"
    
    # Strip again
    name = name.strip()
    return name
new_df['Slack Display Name'] = new_df['Slack Display Name'].apply(clean_slack_name)

In [ ]:
# Define columns to preserve (all except helper column)
cols_to_keep = [col for col in new_df.columns if col != 'Name_Clean']

# Group by cleaned name, aggregate: take first non-null value
clean_df = new_df.groupby('Slack Display Name', as_index=False).agg(
    lambda x: x.dropna().iloc[0] if not x.dropna().empty else None
)

# Drop the helper column
clean_df = clean_df.drop(columns=['Slack Display Name'])

# Reset index
clean_df = clean_df.reset_index(drop=True)

print(f"Original rows: {len(new_df)}")
print(f"Unique people (after cleaning): {len(clean_df)}")