In [144]:
import pandas as pd

In [145]:
df1 = pd.read_excel('C:/Users/USER/OneDrive/Documents/HNG_Internship_Git/Stage_8/Stage8_New/da/Stage 1 Score sheet da.xlsx')
df2 = pd.read_excel('C:/Users/USER/OneDrive/Documents/HNG_Internship_Git/Stage_8/Stage8_New/da/Stage 2 Score Sheet DA.xlsx')
df3 = pd.read_excel('C:/Users/USER/OneDrive/Documents/HNG_Internship_Git/Stage_8/Stage8_New/da/Stage 3 Score Sheet DA.xlsx')
df4 = pd.read_excel('C:/Users/USER/OneDrive/Documents/HNG_Internship_Git/Stage_8/Stage8_New/da/Stage 4 Score Sheet DA.xlsx')
df5 = pd.read_excel('C:/Users/USER/OneDrive/Documents/HNG_Internship_Git/Stage_8/Stage8_New/da/Stage 7 Score Sheet DA.xlsx')

In [146]:
df1.shape,df2.shape,df3.shape,df4.shape,df5.shape

((517, 5), (279, 6), (261, 6), (110, 4), (34, 4))

In [147]:
df1.head()

,Slack Display Name,Slack Email,Total,Pass/Fail,Premium Promotion
0,Ruby_C,chizobaokakpu65@gmail.com,8.95,Pass,NaN
1,KwasakuS,kwasaku6@gmail.com,8.80,Pass,NaN
2,Anyanwu Emmanuella Eberechukwu,anastasiaanyanwu1@gmail.com,8.70,Pass,NaN
3,Dominic Kishatingunimye,dominiqkish@gmail.com,8.50,Pass,NaN
4,EnochA 1️⃣,apehenoch@gmail.com,8.30,Pass,NaN

In [149]:
df1.columns = ['Slack Display Name', 'Slack Email', 'Stage1_Total', 'Stage1_Pass_Fail',
       'Premium Promotion']

In [150]:
df1.rename(columns={
     'Stage1_Total' : 'Stage1_Cummulative Score'
    
}, inplace=True)

In [151]:
df1.head()

,Slack Display Name,Slack Email,Stage1_Cummulative Score,Stage1_Pass_Fail,Premium Promotion
0,Ruby_C,chizobaokakpu65@gmail.com,8.95,Pass,NaN
1,KwasakuS,kwasaku6@gmail.com,8.80,Pass,NaN
2,Anyanwu Emmanuella Eberechukwu,anastasiaanyanwu1@gmail.com,8.70,Pass,NaN
3,Dominic Kishatingunimye,dominiqkish@gmail.com,8.50,Pass,NaN
4,EnochA 1️⃣,apehenoch@gmail.com,8.30,Pass,NaN

In [152]:
df2.head()

,Slack Display Name,Slack Email,TASK A Total,Task B Total,Cummulative Score,Pass/Fail
0,jaycarlx,molokwuchibuzorchristian@gmail.com,46.2700,40.0,8.62700,Pass
1,MayowaO,NaN,40.5000,44.5,8.50000,Pass
2,Mariam-O,Princesstonni01@gmail.con,42.0000,41.0,8.30000,Pass
3,el3ctronar,paulonko000@gmail.com,41.5625,40.7,8.22625,Pass
4,MosunmolaO,adenijimosunmolao@gmail.com,42.0000,40.0,8.20000,Pass

In [153]:
df2.columns = ['Slack Display Name', 'Slack Email', 'TASK A Total', 'Task B Total', 'Stage2_Cummulative Score', 'Stage2_Pass/Fail',]

In [154]:
df3.head()

  Slack Display Name  Group  3A Score   3B Score   Cummulative  Pass / Fail
0            Aminat B    A4       4.70       4.20          8.90        Pass
1         AbdulsamadK    A4       4.70       4.10          8.80        Pass
2    @Maureen Mwenswa    E4       4.30       4.10          8.40        Pass
3           @COTworks    D2       3.68       4.40          8.08        Pass
4          AdaezeELU     A4       4.70       3.35          8.05        Pass

In [155]:
df3.columns = ['Slack Display Name', 'Group', '3A Score', '3B Score', 'Stage3_Cummulative Score', 'Stage3_Pass/Fail',]

In [156]:
df4.head()

  Slack Display Name                      Slack Email  Cummulative Pass/Fail
0             SodiqA          adisasodiq544@gmail.com        8.290      Pass
1              MubaX         lawalademola71@gmail.com        8.080      Pass
2            KossieO  Maureenkosisochukwu97@gmail.com        7.975      Pass
3        AbdulsamadK         kudehinbusamad@gmail.com        7.900      Pass
4      Josh Le Frais           joshuaamadi8@gmail.com        7.780      Pass

In [157]:
df4.columns = ['Slack Display Name', 'Slack Email', 'Stage4_Cummulative Score', 'Stage4_Pass/Fail',]

In [161]:
df5.head()

,Slack Display Name,Slack Email,Stage5_Cummulative Score,Stage5_Pass/Fail
0,@KossieO (Takeda),wz7dwtksv4@privaterelay.appleid.com,9.10,Pass
1,@Pulse Analytics,@pulseanalytucs.io@gmail.com,8.50,Pass
2,Daisy Ige,igedaisy@gmail.com,7.95,Pass
3,Favour K,kalufayvor@gmail.com,7.85,Pass
4,MubaX_Team_Baihu_DA,lawalademola71@gmail.com,7.85,Pass

In [160]:
df5.columns = ['Slack Display Name', 'Slack Email', 'Stage5_Cummulative Score', 'Stage5_Pass/Fail',]

In [162]:
new_df = df1.merge(df2, on=['Slack Display Name', 'Slack Email'], how='outer')\
    .merge(df3, on=['Slack Display Name'], how='outer')\
    .merge(df4, on=['Slack Display Name', 'Slack Email'], how='outer')\
    .merge(df5, on=['Slack Display Name', 'Slack Email'], how='outer')

In [163]:
new_df.head()

,Slack Display Name,Slack Email,Stage1_Cummulative Score,Stage1_Pass_Fail,Premium Promotion,TASK A Total,Task B Total,Stage2_Cummulative Score,Stage2_Pass/Fail,Group,3A Score,3B Score,Stage3_Cummulative Score,Stage3_Pass/Fail,Stage4_Cummulative Score,Stage4_Pass/Fail,Stage5_Cummulative Score,Stage5_Pass/Fail
0,--Fortunate--,lovepaul869@gmail.com,7.5,Pass,NaN,40.19,30.0,7.019,Pass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4tuneDee,chidaddy.fortune@gmail.com,6.0,Pass,NaN,30.50,0.0,3.050,Fail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,@ Shafe Oluwadamilola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I1,2.930,0.00,2.930,Fail,NaN,NaN,NaN,NaN
3,@ Tayo_Akinpelu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D3,3.200,2.40,5.600,Fail,NaN,NaN,NaN,NaN
4,@ Victoria .O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F5,2.767,2.44,5.207,Fail,NaN,NaN,NaN,NaN

In [164]:
new_df.isnull().sum()

Slack Display Name            0
Slack Email                 228
Stage1_Cummulative Score    348
Stage1_Pass_Fail            348
Premium Promotion           804
TASK A Total                588
Task B Total                587
Stage2_Cummulative Score    587
Stage2_Pass/Fail            587
Group                       601
3A Score                    601
3B Score                    601
Stage3_Cummulative Score    601
Stage3_Pass/Fail            601
Stage4_Cummulative Score    756
Stage4_Pass/Fail            756
Stage5_Cummulative Score    832
Stage5_Pass/Fail            832
dtype: int64

In [165]:
new_df.sort_values("Slack Display Name")

,Slack Display Name,Slack Email,Stage1_Cummulative Score,Stage1_Pass_Fail,Premium Promotion,TASK A Total,Task B Total,Stage2_Cummulative Score,Stage2_Pass/Fail,Group,3A Score,3B Score,Stage3_Cummulative Score,Stage3_Pass/Fail,Stage4_Cummulative Score,Stage4_Pass/Fail,Stage5_Cummulative Score,Stage5_Pass/Fail
0,--Fortunate--,lovepaul869@gmail.com,7.5,Pass,NaN,40.1900,30.0,7.01900,Pass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4tuneDee,chidaddy.fortune@gmail.com,6.0,Pass,NaN,30.5000,0.0,3.05000,Fail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,@ Shafe Oluwadamilola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I1,2.930,0.00,2.930,Fail,NaN,NaN,NaN,NaN
3,@ Tayo_Akinpelu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D3,3.200,2.40,5.600,Fail,NaN,NaN,NaN,NaN
4,@ Victoria .O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F5,2.767,2.44,5.207,Fail,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,ugo_c_ugo,gloryadigwe33@gmail.com,6.0,Pass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
862,uog_c_ugo,gloryadigwe33@gmail.com,NaN,NaN,NaN,39.8625,0.0,3.98625,Fail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
863,vee,violet.ehiaguina26@gmail.com,3.0,Fail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
864,yunana,danharuna04@gmail.com,5.5,Fail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
865,yunana,danharuna04@gmail.com,0.0,Fail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [173]:
def clean_slack_name(name):
    if pd.isna(name):
        return ""
    # Remove @ symbol
    name = str(name).replace('@', '').strip()
     # Remove emojis/suffixes like "1️⃣", "2️⃣", "3️⃣", "4️⃣"
    import re
    name = re.sub(r'[0-9]️⃣|\s*\d+\s*', '', name).strip()
    # Remove extra spaces
    name = ' '.join(name.split())
    return name.lower()

new_df['Name_Clean'] = new_df['Slack Display Name'].apply(clean_slack_name)

In [175]:
# Show only the original and cleaned name for first 10 rows
print(new_df[['Slack Display Name', 'Name_Clean']].head(10))

      Slack Display Name           Name_Clean
0          --Fortunate--        --fortunate--
1               4tuneDee              tunedee
2  @ Shafe Oluwadamilola  shafe oluwadamilola
3        @ Tayo_Akinpelu        tayo_akinpelu
4          @ Victoria .O          victoria .o
5         @--Fortunate--        --fortunate--
6              @4tuneDee              tunedee
7                 @AGina                agina
8         @Aanuoluwapo A        aanuoluwapo a
9            @AbigailAL             abigailal

In [180]:
new_df['Slack Display Name'] = new_df['Name_Clean']
new_df.drop(columns=['Name_Clean'], inplace=True)  # Optional: remove helper column

In [184]:
new_df.head()

,Slack Display Name,Slack Email,Stage1_Cummulative Score,Stage1_Pass_Fail,Premium Promotion,TASK A Total,Task B Total,Stage2_Cummulative Score,Stage2_Pass/Fail,Group,3A Score,3B Score,Stage3_Cummulative Score,Stage3_Pass/Fail,Stage4_Cummulative Score,Stage4_Pass/Fail,Stage5_Cummulative Score,Stage5_Pass/Fail,Name_Clean
0,--fortunate--,lovepaul869@gmail.com,7.5,Pass,NaN,40.19,30.0,7.019,Pass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,--fortunate--
1,tunedee,chidaddy.fortune@gmail.com,6.0,Pass,NaN,30.50,0.0,3.050,Fail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tunedee
2,shafe oluwadamilola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I1,2.930,0.00,2.930,Fail,NaN,NaN,NaN,NaN,shafe oluwadamilola
3,tayo_akinpelu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D3,3.200,2.40,5.600,Fail,NaN,NaN,NaN,NaN,tayo_akinpelu
4,victoria .o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F5,2.767,2.44,5.207,Fail,NaN,NaN,NaN,NaN,victoria .o

In [182]:
def clean_slack_name(name):
    if pd.isna(name):
        return ""
    name = str(name).strip()  # Strip leading/trailing whitespace
    # Remove @ symbol and any surrounding spaces
    name = re.sub(r'^@+|@+$', '', name).strip()
    # Remove emojis/suffixes like "1️⃣", "2️⃣"
    name = re.sub(r'[0-9]️⃣|\s*\d+\s*', '', name).strip()
    # Normalize spaces
    name = ' '.join(name.split())
    return name.lower()

In [183]:
new_df['Name_Clean'] = new_df['Slack Display Name'].apply(clean_slack_name)

In [185]:
new_df['Slack Display Name'] = new_df['Name_Clean']
new_df.drop(columns=['Name_Clean'], inplace=True)  # Optional: remove helper column

In [188]:
# Show only the original and cleaned name for first 10 rows
print(new_df[['Slack Display Name']].head(10))

    Slack Display Name
0        --fortunate--
1              tunedee
2  shafe oluwadamilola
3        tayo_akinpelu
4          victoria .o
5        --fortunate--
6              tunedee
7                agina
8        aanuoluwapo a
9            abigailal

In [189]:
new_df.head()

,Slack Display Name,Slack Email,Stage1_Cummulative Score,Stage1_Pass_Fail,Premium Promotion,TASK A Total,Task B Total,Stage2_Cummulative Score,Stage2_Pass/Fail,Group,3A Score,3B Score,Stage3_Cummulative Score,Stage3_Pass/Fail,Stage4_Cummulative Score,Stage4_Pass/Fail,Stage5_Cummulative Score,Stage5_Pass/Fail
0,--fortunate--,lovepaul869@gmail.com,7.5,Pass,NaN,40.19,30.0,7.019,Pass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tunedee,chidaddy.fortune@gmail.com,6.0,Pass,NaN,30.50,0.0,3.050,Fail,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,shafe oluwadamilola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I1,2.930,0.00,2.930,Fail,NaN,NaN,NaN,NaN
3,tayo_akinpelu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D3,3.200,2.40,5.600,Fail,NaN,NaN,NaN,NaN
4,victoria .o,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F5,2.767,2.44,5.207,Fail,NaN,NaN,NaN,NaN

In [191]:
# Define columns to preserve (all except helper column)
cols_to_keep = [col for col in new_df.columns if col != 'Name_Clean']

# Group by cleaned name, aggregate: take first non-null value
clean_df = new_df.groupby('Slack Display Name', as_index=False).agg(
    lambda x: x.dropna().iloc[0] if not x.dropna().empty else None
)

# Drop the helper column
clean_df = clean_df.drop(columns=['Slack Display Name'])

# Reset index
clean_df = clean_df.reset_index(drop=True)

print(f"Original rows: {len(new_df)}")
print(f"Unique people (after cleaning): {len(clean_df)}")

Original rows: 866
Unique people (after cleaning): 599

In [199]:
def clean_name(name):
    if pd.isna(name):
        return ""
    name = str(name).strip()
    # Remove @ at start
    name = re.sub(r'^@+', '', name)
    # Remove common emoji suffixes like 1️⃣, 2️⃣, 3️⃣, etc.
    name = re.sub(r'[0-9]️⃣', '', name)
    # Remove other emojis or special suffixes (optional)
    name = re.sub(r'\s*[0-9]+[️⃣]*\s*$', '', name)  # trailing numbers
    name = ' '.join(name.split())  # normalize spaces
    return name.lower()

new_df['Name_Clean'] = new_df['Slack Display Name'].apply(clean_name)

In [207]:
new_df['Slack Email'] = new_df['Slack Email'].fillna("").astype(str)
new_df['Email_Clean'] = new_df['Slack Email'].str.lower().str.strip()

In [209]:
new_df['Person_ID'] = new_df['Email_Clean'].replace("", pd.NA).fillna(new_df['Name_Clean'])

In [210]:
def first_non_null(series):
    non_null = series.dropna()
    if non_null.empty:
        return None
    # Prefer non-"No Score", non-empty, non-placeholder values
    meaningful = non_null[~non_null.astype(str).isin(["", "No Score", "nan"])]
    if not meaningful.empty:
        return meaningful.iloc[0]
    return non_null.iloc[0]

In [212]:
clean_df = new_df.groupby('Person_ID').agg(first_non_null)

In [216]:
name_priority = (
    new_df[new_df['Slack Display Name'].notna()]
    .groupby('Person_ID')['Slack Display Name']
    .apply(lambda x: x.iloc[0])  
)
clean_df['Slack Display Name'] = name_priority

In [217]:
cols = ['Slack Display Name', 'Slack Email'] + [col for col in clean_df.columns if col not in ['Slack Display Name', 'Slack Email']]
clean_df = clean_df[cols]

In [218]:
clean_df = clean_df.reset_index(drop=True)

In [220]:
clean_df.to_excel(r"C:\Users\USER\OneDrive\Documents\HNG_Internship_Git\Stage_8\HNG13_Scores_Cleaned.xlsx", index=False)

# print(f"Original rows: {len(df)}")
# print(f"Cleaned unique people: {len(clean_df)}")

In [54]:
def score_grade(score):
    if pd.isnull(score):
        return 'No Score'
    elif score >= 8:
        return 'Distinction'
    elif score >= 7:
        return 'Second Class Upper'
    elif score >= 6:
        return 'Third Class'
    elif score >= 5:
        return 'Let my people go'
    else:
        return 'Fail'

In [58]:
new_df["Stage1_perf_grade"] = new_df["Stage1_Cummulative Score"].apply(score_grade)
new_df["Stage2_perf_grade"] = new_df["Stage2_Cummulative Score"].apply(score_grade)
new_df["Stage3_perf_grade"] = new_df["Stage3_Cummulative Score"].apply(score_grade)
new_df["Stage4_perf_grade"] = new_df["Stage4_Cummulative Score"].apply(score_grade)
new_df["Stage5_perf_grade"] = new_df["Stage5_Cummulative Score"].apply(score_grade)

In [59]:
new_df.head()

,Slack Display Name,Slack Email,Stage1_Cummulative Score,Stage1_Pass_Fail,Premium Promotion,TASK A Total,Task B Total,Stage2_Cummulative Score,Stage2_Pass/Fail,Group,...,Stage3_Pass/Fail,Stage4_Cummulative Score,Stage4_Pass/Fail,Stage5_Cummulative Score,Stage5_Pass/Fail,Stage1_perf_grade,Stage2_perf_grade,Stage3_perf_grade,Stage4_perf_grade,Stage5_perf_grade
0,--Fortunate--,lovepaul869@gmail.com,7.5,Pass,NaN,40.19,30.0,7.019,Pass,NaN,...,NaN,NaN,NaN,NaN,NaN,Second Class Upper,Second Class Upper,No Score,No Score,No Score
1,4tuneDee,chidaddy.fortune@gmail.com,6.0,Pass,NaN,30.50,0.0,3.050,Fail,NaN,...,NaN,NaN,NaN,NaN,NaN,Third Class,Fail,No Score,No Score,No Score
2,@ Shafe Oluwadamilola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I1,...,Fail,NaN,NaN,NaN,NaN,No Score,No Score,Fail,No Score,No Score
3,@ Tayo_Akinpelu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D3,...,Fail,NaN,NaN,NaN,NaN,No Score,No Score,Let my people go,No Score,No Score
4,@ Victoria .O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F5,...,Fail,NaN,NaN,NaN,NaN,No Score,No Score,Let my people go,No Score,No Score

In [68]:
new_df["Stage1_perf_grade"].value_counts()
# new_df["Stage2_perf_grade"].value_counts()
# new_df["Stage3_perf_grade"].value_counts()
# new_df["Stage4_perf_grade"].value_counts()
# new_df["Stage5_perf_grade"].value_counts()

Stage1_perf_grade
No Score              348
Third Class           163
Fail                  156
Second Class Upper     90
Let my people go       90
Distinction            19
Name: count, dtype: int64

In [75]:
import re

def clean_slack_name(name):
    if pd.isna(name): 
        return ""
    name = str(name).strip()
     # Remove @ prefix
    if sname.startswith('@'):
        name = name[1:].strip()

In [84]:
import re

def clean_slack_name(name):
    if pd.isna(name): 
        return ""
    name = str(name).strip()
    
    # Remove @ prefix
    if name.startswith('@'):
        name = name[1:].strip()
    
    # Remove trailing numbers, emojis, symbols like 1️⃣, 2️⃣, etc.
    # Also remove " (1)", " [1]", etc.
    name = re.sub(r'[0-9]+️⃣|\s*\([0-9]+\)|\s*\[[0-9]+\]|\s*[1-9]$', '', name)
    name = re.sub(r'\s*;.*', '', name)  # e.g., "FaithA ;)"
    name = re.sub(r'\s+\d+$', '', name)  # e.g., "FaithCK 4"
    
    # Strip again
    name = name.strip()
    return name
new_df['Slack Display Name'] = new_df['Slack Display Name'].apply(clean_slack_name)

In [92]:
new_df.head()

,Slack Display Name,Slack Email,Stage1_Cummulative Score,Stage1_Pass_Fail,Premium Promotion,TASK A Total,Task B Total,Stage2_Cummulative Score,Stage2_Pass/Fail,Group,...,Stage3_Pass/Fail,Stage4_Cummulative Score,Stage4_Pass/Fail,Stage5_Cummulative Score,Stage5_Pass/Fail,Stage1_perf_grade,Stage2_perf_grade,Stage3_perf_grade,Stage4_perf_grade,Stage5_perf_grade
0,--Fortunate--,lovepaul869@gmail.com,7.5,Pass,NaN,40.19,30.0,7.019,Pass,NaN,...,NaN,NaN,NaN,NaN,NaN,Second Class Upper,Second Class Upper,No Score,No Score,No Score
1,4tuneDee,chidaddy.fortune@gmail.com,6.0,Pass,NaN,30.50,0.0,3.050,Fail,NaN,...,NaN,NaN,NaN,NaN,NaN,Third Class,Fail,No Score,No Score,No Score
2,Shafe Oluwadamilola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I1,...,Fail,NaN,NaN,NaN,NaN,No Score,No Score,Fail,No Score,No Score
3,Tayo_Akinpelu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D3,...,Fail,NaN,NaN,NaN,NaN,No Score,No Score,Let my people go,No Score,No Score
4,Victoria .O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F5,...,Fail,NaN,NaN,NaN,NaN,No Score,No Score,Let my people go,No Score,No Score

In [93]:
# Define columns to preserve (all except helper column)
cols_to_keep = [col for col in new_df.columns if col != 'Name_Clean']

# Group by cleaned name, aggregate: take first non-null value
clean_df = new_df.groupby('Slack Display Name', as_index=False).agg(
    lambda x: x.dropna().iloc[0] if not x.dropna().empty else None
)

# Drop the helper column
clean_df = clean_df.drop(columns=['Slack Display Name'])

# Reset index
clean_df = clean_df.reset_index(drop=True)

print(f"Original rows: {len(new_df)}")
print(f"Unique people (after cleaning): {len(clean_df)}")

Original rows: 866
Unique people (after cleaning): 639

In [94]:
clean_df.head()

,Slack Email,Stage1_Cummulative Score,Stage1_Pass_Fail,Premium Promotion,TASK A Total,Task B Total,Stage2_Cummulative Score,Stage2_Pass/Fail,Group,3A Score,...,Stage3_Pass/Fail,Stage4_Cummulative Score,Stage4_Pass/Fail,Stage5_Cummulative Score,Stage5_Pass/Fail,Stage1_perf_grade,Stage2_perf_grade,Stage3_perf_grade,Stage4_perf_grade,Stage5_perf_grade
0,lovepaul869@gmail.com,7.5,Pass,None,40.19,30.0,7.019,Pass,F5,2.767,...,Pass,NaN,None,NaN,None,Second Class Upper,Second Class Upper,No Score,No Score,No Score
1,chidaddy.fortune@gmail.com,6.0,Pass,None,30.50,0.0,3.050,Fail,E4,4.300,...,Fail,NaN,None,NaN,None,Third Class,Fail,No Score,No Score,No Score
2,kareemojoaishah@gmail.com,5.5,Fail,None,NaN,NaN,NaN,None,None,NaN,...,None,NaN,None,NaN,None,Let my people go,No Score,No Score,No Score,No Score
3,ahmedsaidat4@gmail.com,0.0,Fail,None,NaN,NaN,NaN,None,None,NaN,...,None,NaN,None,NaN,None,Fail,No Score,No Score,No Score,No Score
4,axemokha@gmail.com,NaN,None,None,14.75,11.5,2.625,Fail,None,NaN,...,None,5.5,Fail,NaN,None,No Score,Fail,No Score,Let my people go,No Score