In [3]:
import pandas as pd
import requests
from serpapi import GoogleSearch
from bs4 import BeautifulSoup
from concurrent.futures import ThreadPoolExecutor, as_completed
import time

In [ ]:
finalbank = pd.read_csv("final_bank_seo_data.csv")
finalbank.head()

,Keyword,Bank Name Used,Rank Position,Competition,Competition Index,Search Volume,Bank Name,Year,Revenue_in billions,Source
0,mortgage loans best rates,firstbank,3,LOW,0,590,First Bank of Nigeria Limited,2024.0,"NGN 3,200.00",https://first-holdco.com/wp-content/uploads/20...
1,mortgage loans best rates,stanbicibtc,4,LOW,0,590,Stanbic IBTC Bank Plc,2024.0,NGN 823.31,https://africanfinancials.com/document/ng-ibtc...
2,mortgage loans best rates,gtbank,7,LOW,0,590,Guaranty Trust Bank Limited,2024.0,NGN 467.85,https://gtbank-plc.files.svdcdn.com/production...
3,best home equity loans,stanbicibtc,1,LOW,7,260,Stanbic IBTC Bank Plc,2024.0,NGN 823.31,https://africanfinancials.com/document/ng-ibtc...
4,best home equity loans,firstbank,5,LOW,7,260,First Bank of Nigeria Limited,2024.0,"NGN 3,200.00",https://first-holdco.com/wp-content/uploads/20...

In [26]:
import pandas as pd

# Convert only numeric-like values to integers and label them
def format_year(val):
    try:
        # Try to convert numeric strings/floats like '2024.0' or 2024
        year_int = int(float(val))
        return f"Year {year_int}"
    except (ValueError, TypeError):
        # If it's not numeric, keep it unchanged
        return val

finalbank['Year'] = finalbank['Year'].apply(format_year)

finalbank.head()

,Keyword,Bank Name Used,Rank Position,Competition,Competition Index,Search Volume,Bank Name,Year,Revenue_in billions,Source
0,mortgage loans best rates,firstbank,3,LOW,0,590,First Bank of Nigeria Limited,Year 2024,"NGN 3,200.00",https://first-holdco.com/wp-content/uploads/20...
1,mortgage loans best rates,stanbicibtc,4,LOW,0,590,Stanbic IBTC Bank Plc,Year 2024,NGN 823.31,https://africanfinancials.com/document/ng-ibtc...
2,mortgage loans best rates,gtbank,7,LOW,0,590,Guaranty Trust Bank Limited,Year 2024,NGN 467.85,https://gtbank-plc.files.svdcdn.com/production...
3,best home equity loans,stanbicibtc,1,LOW,7,260,Stanbic IBTC Bank Plc,Year 2024,NGN 823.31,https://africanfinancials.com/document/ng-ibtc...
4,best home equity loans,firstbank,5,LOW,7,260,First Bank of Nigeria Limited,Year 2024,"NGN 3,200.00",https://first-holdco.com/wp-content/uploads/20...

In [36]:
# # Step 1: Convert to numeric safely (ignore text like 'Year <NA>')
# finalbank['Year'] = pd.to_numeric(finalbank['Year'], errors='coerce')

# # Step 2: Drop rows with missing year (optional)
# # finalbank = finalbank.dropna(subset=['Year'])

# # Step 3: Convert year to full datetime — 31st December of that year
# finalbank['Year'] = pd.to_datetime(finalbank['Year'].astype('Int64').astype(str) + '-12-31', errors='coerce')

# finalbank.head()
finalbank.to_csv("final_seo_datenew.csv", index=False)

In [31]:
# Extract the numeric part of the 'Year' column into a new column 'year_new'
finalbank['year_new'] = (
    finalbank['Year']
    .astype(str)                              # ensure text type
    .str.extract(r'(\d{4})')                  # extract 4-digit year pattern
    .astype(float)                            # convert to numeric if needed
    .astype('Int64')                          # allow missing values safely
)

finalbank.head()
# Update the 'Year' column to be of Int64 type


finalbank.to_csv("final_seo_data.csv", index=False)

In [29]:
# Extract numeric year from text like "Year 2024"
finalbank['Year'] = finalbank['Year'].astype(str).str.extract(r'(\d{4})')

# Convert to integer if you want it as a number (optional)
finalbank['Year'] = finalbank['Year'].astype('Int64')

finalbank.head()
finalbank.to_csv("final_seo_data.csv", index=False)

In [ ]:
# Step 1: Load your existing CSV
df = pd.read_csv("keywords.csv")
keywords = df["Keyword Text"].tolist()
# Step 2: Define Nigerian banks to look for
banks = [
    "accessbank", "gtbank", "zenithbank", "firstbank", "uba",
    "polarisbank", "fcmb", "unionbank", "sterlingbank",
    "fidelitybank", "stanbicibtc", "providusbank", "keystonebank",
    "jaizbank", "tajbank", "wema", "globank"
]
api_key = "4a0ea474f3594ea972db084760235e10e30718a43a9bbccd79425dcfb4e7c736" 
results = []

KeyError: 'Keyword Text'

In [ ]:
# Step 3: Scrape Google search results
api_key = "4a0ea474f3594ea972db084760235e10e30718a43a9bbccd79425dcfb4e7c736" 
def fetch_data(kw):
    params = {
        "engine": "google",
        "q": f"{kw} Nigeria",
        "api_key": api_key,
        "num": "10"}
    search = GoogleSearch(params)
    data = search.get_dict()
    output = []

    if "organic_results" in data:
        for idx, item in enumerate(data["organic_results"], start=1):
            link = item.get("link", "").lower()
            for bank in banks:
                if bank in link:
                    output.append({
                        "Keyword": kw,
                        "Bank": bank,
                        "Rank Position": idx
                    })
    return output
# Use ThreadPoolExecutor for parallel requests
with ThreadPoolExecutor(max_workers=5) as executor:
    future_to_kw = {executor.submit(fetch_data, kw): kw for kw in keywords}
    for future in as_completed(future_to_kw):
        try:
            results.extend(future.result())
        except Exception as e:
            print(f"Error with {future_to_kw[future]}: {e}")

# Save results
rank_df = pd.DataFrame(results)
rank_df.to_csv("bank_rank_results_fast.csv", index=False)
print("Fast bank ranking data saved successfully!")

In [ ]:
api_key = "4a0ea474f3594ea972db084760235e10e30718a43a9bbccd79425dcfb4e7c736" 
def fetch_data(kw):
    params = {
        "engine": "google",
        "q": f"{kw} Nigeria",
        "api_key": api_key,
        "num": "10"}
    search = GoogleSearch(params)
    data = search.get_dict()
    output = []

    if "organic_results" in data:
        for idx, item in enumerate(data["organic_results"], start=1):
            link = item.get("link", "").lower()
            for bank in banks:
                if bank in link:
                    output.append({
                        "Keyword": kw,
                        "Bank": bank,
                        "Rank Position": idx
                    })
    return output

with ThreadPoolExecutor(max_workers=5) as executor:
    future_to_kw = {executor.submit(fetch_data, kw): kw for kw in keywords}
    for future in as_completed(future_to_kw):
        try:
            results.extend(future.result())
        except Exception as e:
            print(f"Error with {future_to_kw[future]}: {e}")

rank_df = pd.DataFrame(results)
rank_df.to_csv("bank_rank_results_fast.csv", index=False)
print("Fast bank ranking data saved successfully!")

In [ ]:
# from concurrent.futures import ThreadPoolExecutor, as_completed
# import pandas as pd
# from serpapi import GoogleSearch

# # Make sure you have your API key set up
# api_key = "86b055844b618c2db55fa39b217f97e471d7330b355d5b34e527cd031a2c66ea"

# # Example list of keywords and banks
# keywords = ["bank loans", "mobile banking", "credit cards"]
# banks = ["accessbank", "gtbank", "zenithbank", "uba", "firstbank"]

# results = []

# Step 3: Scrape Google search results
def fetch_data(kw):
    params = {
        "engine": "google",
        "q": f"{kw} Nigeria",
        "api_key": api_key,
        "num": "10"
    }
    search = GoogleSearch(params)
    data = search.get_dict()

    output = []

    if "organic_results" in data:
        for idx, item in enumerate(data["organic_results"], start=1):
            link = item.get("link", "").lower()
            for bank in banks:
                if bank in link:
                    output.append({
                        "Keyword": kw,
                        "Bank": bank,
                        "Rank Position": idx
                    })
    return output

# Use ThreadPoolExecutor for parallel requests
with ThreadPoolExecutor(max_workers=5) as executor:
    future_to_kw = {executor.submit(fetch_data, kw): kw for kw in keywords}
    for future in as_completed(future_to_kw):
        try:
            results.extend(future.result())
        except Exception as e:
            print(f"Error with {future_to_kw[future]}: {e}")

# Save results
rank_df = pd.DataFrame(results)
rank_df.to_csv("bank_rank_results_fast.csv", index=False)
print("✅ Fast bank ranking data saved successfully!")

Error with banks that offer loans: HTTPSConnectionPool(host='serpapi.com', port=443): Max retries exceeded with url: /search?engine=google&q=banks+that+offer+loans+Nigeria&api_key=4a0ea474f3594ea972db084760235e10e30718a43a9bbccd79425dcfb4e7c736&num=10&output=json&source=python (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:1077)')))

In [ ]:
import pandas as pd

# Load all files
bankranks = pd.read_csv("bank_rank_results.csv")
bankrevenues = pd.read_csv("bank_revenues.csv")
keywords = pd.read_csv("keywords.csv")

print("Files loaded successfully.")
bankranks.head()
keywords.head()
bankrevenues.head()

Files loaded successfully.

,Bank Name Used,Bank Name,Year,Revenue_in billions,Source
0,Accessbank,Access Bank Plc,2024.0,"NGN 4,878.00",https://accessholdingsplc.com/wp-content/uploa...
1,Gtbank,Guaranty Trust Bank Limited,2024.0,NGN 467.85,https://gtbank-plc.files.svdcdn.com/production...
2,Zenithbank,Zenith Bank Plc,2024.0,"NGN 3,970.00",https://africanfinancials.com/document/ng-zeni...
3,Firstbank,First Bank of Nigeria Limited,2024.0,"NGN 3,200.00",https://first-holdco.com/wp-content/uploads/20...
4,UBA,United Bank for Africa Plc,2024.0,"NGN 3,180.00",https://www.ubagroup.com/investors/financial-r...

In [ ]:
ranks.rename(columns={'Bank(s)': 'Bank'}, inplace=True)
keywords.rename(columns={'Bank(s)': 'Bank'}, inplace=True)

bankranks.head()

NameError: name 'pd' is not defined

In [38]:
# import pandas as pd

# # Load both datasets
# keywords = pd.read_csv("keywords.csv")
# ranks = pd.read_csv("bank_rank_results.csv")

# Filter keywords that appear in bank_rank_results
keywords_filtered = keywords[keywords["Keyword Text"].isin(ranks["Keyword"].unique())]

# Save the filtered version
keywords_filtered.to_csv("keywords_filtered.csv", index=False)
print("✅ Filtered keywords saved successfully!")

keywords_filtered.head()

NameError: name 'ranks' is not defined

In [57]:
print("Ranks columns:", ranks.columns.tolist())
print("Revenues columns:", revenues.columns.tolist())
print("Keywords columns:", keywords.columns.tolist())


# keywords_filtered.columns: ['Keyword', 'Competition', 'Competition Index', 'Search Volume' ]
# keywords_filtered = keywords[keywords["Keyword"].isin(ranks["Keyword"])]

keywords_filtered = keywords_filtered.rename(columns={"Keyword Text": "Keyword"})
print("Keywords Filtered columns:", keywords_filtered.columns.tolist())

NameError: name 'ranks' is not defined

In [63]:
# Check unique bank names
print(ranks['Bank Name Used'].unique())
print(revenues['Bank Name Used'].unique())

# Remove leading/trailing spaces and convert to lowercase
ranks['Bank Name Used'] = ranks['Bank Name Used'].str.strip().str.lower()
revenues['Bank Name Used'] = revenues['Bank Name Used'].str.strip().str.lower()

NameError: name 'ranks' is not defined

In [2]:
import pandas as pd
merged1 = pd.merge(ranks, keywords_filtered, on='Keyword', how='left')
final_merged = pd.merge(merged1, revenues, on='Bank Name Used', how='left')


# # Step 1: Merge ranks with keywords_filtered on 'Keyword'
# merged1 = pd.merge(ranks, keywords_filtered, on='Keyword', how='left')

# # # Step 2: Merge the result with revenues on 'Bank Name Used'
# final_merged = pd.merge(merged1, revenues, on='Bank Name Used', how='left')

# # # Optional: reorder columns if needed
# final_merged = final_merged[['Keyword', 'Competition', 'Competition Index', 'Search Volume',
#                              'Bank Name Used', 'Rank Position', 'Bank Name', 'Year', 'Revenue_in billions', 'Source']]

# # # Check result
final_merged.head()
# Save final merged dataframe
final_merged.to_csv("final_seo_data.csv", index=False)

NameError: name 'ranks' is not defined

In [ ]:
df = pd.read_csv("final_bank_seo_data.csv")

NameError: name 'pd' is not defined